import { InsertUniversity } from "@shared/schema";

export const universityMockData: InsertUniversity[] = [
  {
    name: "Harvard University",
    location: "Cambridge, Massachusetts, USA",
    country: "United States",
    worldRanking: 1,
    acceptanceRate: "5.00",
    tuitionFee: "$54,880",
    studentPopulation: 22000,
    founded: 1636,
    type: "Private Research University",
    endowment: "$53.2 billion",
    studentFacultyRatio: "6:1",
    website: "harvard.edu",
    phone: "+1 (617) 495-1000",
    address: "Cambridge, MA 02138, United States",
    description: "Harvard University is a private Ivy League research university in Cambridge, Massachusetts. Established in 1636, Harvard is the oldest institution of higher education in the United States and among the most prestigious in the world.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Medicine", "Law", "Business", "Engineering", "Liberal Arts"],
    isBookmarked: 0
  },
  {
    name: "Stanford University",
    location: "Stanford, California, USA",
    country: "United States",
    worldRanking: 2,
    acceptanceRate: "4.00",
    tuitionFee: "$58,416",
    studentPopulation: 17000,
    founded: 1885,
    type: "Private Research University",
    endowment: "$37.8 billion",
    studentFacultyRatio: "5:1",
    website: "stanford.edu",
    phone: "+1 (650) 723-2300",
    address: "Stanford, CA 94305, United States",
    description: "Stanford University is a private research university in Stanford, California. Known for its entrepreneurial spirit and proximity to Silicon Valley.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Computer Science", "Engineering", "Business", "Medicine", "Liberal Arts"],
    isBookmarked: 0
  },
  {
    name: "Massachusetts Institute of Technology",
    location: "Cambridge, Massachusetts, USA",
    country: "United States",
    worldRanking: 3,
    acceptanceRate: "7.00",
    tuitionFee: "$57,986",
    studentPopulation: 11000,
    founded: 1861,
    type: "Private Research University",
    endowment: "$27.4 billion",
    studentFacultyRatio: "3:1",
    website: "mit.edu",
    phone: "+1 (617) 253-1000",
    address: "Cambridge, MA 02139, United States",
    description: "MIT is a private research university known for its innovation in science and technology education and research.",
    imageUrl: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Engineering", "Computer Science", "Physics", "Mathematics", "Economics"],
    isBookmarked: 0
  },
  {
    name: "University of Oxford",
    location: "Oxford, England, UK",
    country: "United Kingdom",
    worldRanking: 4,
    acceptanceRate: "15.00",
    tuitionFee: "£9,250",
    studentPopulation: 24000,
    founded: 1096,
    type: "Public Research University",
    endowment: "£6.1 billion",
    studentFacultyRatio: "11:1",
    website: "ox.ac.uk",
    phone: "+44 1865 270000",
    address: "Oxford OX1 2JD, United Kingdom",
    description: "The University of Oxford is a collegiate research university in Oxford, England. It is the oldest university in the English-speaking world.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Philosophy", "Politics", "Economics", "Medicine", "Law"],
    isBookmarked: 0
  },
  {
    name: "University of Cambridge",
    location: "Cambridge, England, UK",
    country: "United Kingdom",
    worldRanking: 5,
    acceptanceRate: "21.00",
    tuitionFee: "£9,250",
    studentPopulation: 23000,
    founded: 1209,
    type: "Public Research University",
    endowment: "£7.1 billion",
    studentFacultyRatio: "11:1",
    website: "cam.ac.uk",
    phone: "+44 1223 337733",
    address: "Cambridge CB2 1TN, United Kingdom",
    description: "The University of Cambridge is a collegiate research university in Cambridge, United Kingdom. Founded in 1209, it is the second-oldest university in the English-speaking world.",
    imageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Natural Sciences", "Engineering", "Mathematics", "Medicine", "Law"],
    isBookmarked: 0
  },
  {
    name: "California Institute of Technology",
    location: "Pasadena, California, USA",
    country: "United States",
    worldRanking: 6,
    acceptanceRate: "3.00",
    tuitionFee: "$60,864",
    studentPopulation: 2200,
    founded: 1891,
    type: "Private Research University",
    endowment: "$3.7 billion",
    studentFacultyRatio: "3:1",
    website: "caltech.edu",
    phone: "+1 (626) 395-6811",
    address: "Pasadena, CA 91125, United States",
    description: "Caltech is a private research university known for its strength in science and engineering.",
    imageUrl: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Physics", "Chemistry", "Biology", "Engineering", "Computer Science"],
    isBookmarked: 0
  },
  {
    name: "Yale University",
    location: "New Haven, Connecticut, USA",
    country: "United States",
    worldRanking: 7,
    acceptanceRate: "6.00",
    tuitionFee: "$62,250",
    studentPopulation: 13000,
    founded: 1701,
    type: "Private Research University",
    endowment: "$42.3 billion",
    studentFacultyRatio: "6:1",
    website: "yale.edu",
    phone: "+1 (203) 432-4771",
    address: "New Haven, CT 06520, United States",
    description: "Yale University is a private Ivy League research university in New Haven, Connecticut.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Liberal Arts", "Law", "Medicine", "Business", "Drama"],
    isBookmarked: 0
  },
  {
    name: "Princeton University",
    location: "Princeton, New Jersey, USA",
    country: "United States",
    worldRanking: 8,
    acceptanceRate: "5.50",
    tuitionFee: "$57,410",
    studentPopulation: 5400,
    founded: 1746,
    type: "Private Research University",
    endowment: "$37.7 billion",
    studentFacultyRatio: "5:1",
    website: "princeton.edu",
    phone: "+1 (609) 258-3000",
    address: "Princeton, NJ 08544, United States",
    description: "Princeton University is a private Ivy League research university in Princeton, New Jersey.",
    imageUrl: "https://images.unsplash.com/photo-1562774053-701939374585?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Engineering", "Public Policy", "Economics", "Computer Science", "Physics"],
    isBookmarked: 0
  },
  {
    name: "University of Toronto",
    location: "Toronto, Ontario, Canada",
    country: "Canada",
    worldRanking: 18,
    acceptanceRate: "43.00",
    tuitionFee: "CAD $61,850",
    studentPopulation: 97000,
    founded: 1827,
    type: "Public Research University",
    endowment: "CAD $2.6 billion",
    studentFacultyRatio: "18:1",
    website: "utoronto.ca",
    phone: "+1 (416) 978-2011",
    address: "Toronto, ON M5S 1A1, Canada",
    description: "The University of Toronto is a public research university in Toronto, Ontario, Canada.",
    imageUrl: "https://images.unsplash.com/photo-1541339907198-e08756dedf3f?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Medicine", "Engineering", "Business", "Arts & Science", "Law"],
    isBookmarked: 0
  },
  {
    name: "University of Melbourne",
    location: "Melbourne, Victoria, Australia",
    country: "Australia",
    worldRanking: 33,
    acceptanceRate: "70.00",
    tuitionFee: "AUD $45,824",
    studentPopulation: 51000,
    founded: 1853,
    type: "Public Research University",
    endowment: "AUD $1.8 billion",
    studentFacultyRatio: "22:1",
    website: "unimelb.edu.au",
    phone: "+61 3 8344 4000",
    address: "Melbourne VIC 3010, Australia",
    description: "The University of Melbourne is a public research university located in Melbourne, Australia.",
    imageUrl: "https://images.unsplash.com/photo-1576495199011-eb94736d05d6?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Medicine", "Law", "Business", "Engineering", "Arts"],
    isBookmarked: 0
  },
  {
    name: "Technical University of Munich",
    location: "Munich, Bavaria, Germany",
    country: "Germany",
    worldRanking: 50,
    acceptanceRate: "8.00",
    tuitionFee: "€150",
    studentPopulation: 45000,
    founded: 1868,
    type: "Public Research University",
    endowment: "€1.2 billion",
    studentFacultyRatio: "15:1",
    website: "tum.de",
    phone: "+49 89 289 01",
    address: "Munich, Bavaria, Germany",
    description: "The Technical University of Munich is a public research university in Munich, Germany.",
    imageUrl: "https://images.unsplash.com/photo-1607013251379-e6eecfffe234?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Engineering", "Technology", "Medicine", "Natural Sciences", "Management"],
    isBookmarked: 0
  },
  {
    name: "University of Tokyo",
    location: "Tokyo, Japan",
    country: "Japan",
    worldRanking: 23,
    acceptanceRate: "30.00",
    tuitionFee: "¥535,800",
    studentPopulation: 28000,
    founded: 1877,
    type: "Public Research University",
    endowment: "¥180 billion",
    studentFacultyRatio: "10:1",
    website: "u-tokyo.ac.jp",
    phone: "+81 3 3812 2111",
    address: "Tokyo 113-8654, Japan",
    description: "The University of Tokyo is a public research university in Tokyo, Japan.",
    imageUrl: "https://images.unsplash.com/photo-1564981797816-1043664bf78d?ixlib=rb-4.0.3&auto=format&fit=crop&w=800&h=400",
    programs: ["Engineering", "Medicine", "Law", "Economics", "Liberal Arts"],
    isBookmarked: 0
  }
];
